# -*- coding: utf-8 -*-
"""chatSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chfDHPbEa6hv6mD03P2IuEtToZa5cJie

####Package Installation
"""

!pip install faiss-cpu langchain langchain-community langchain-google-genai pandas

"""####Imports"""

from langchain_community.document_loaders.csv_loader import CSVLoader
from pathlib import Path
from langchain.chat_models import init_chat_model
from langchain_google_genai import GoogleGenerativeAIEmbeddings
import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"]=userdata.get('GOOGLE_API_KEY')

llm = init_chat_model("gemini-2.5-flash", model_provider="google_genai")

"""####Initiate the Vector Store"""

pip install -qU langchain-huggingface

import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
index = faiss.IndexFlatL2(len(embeddings.embed_query(" ")))
vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={}
)

"""####Create a loader for JSON files"""

pip install jq

from langchain_community.document_loaders import JSONLoader
file_path = 'app_insights.json'

# Define the jq schema to extract data from the JSON.
# This example assumes you want to load the entire JSON content as a single document.
# You may need to adjust the jq_schema based on the structure of your JSON file
# to extract specific fields or arrays.
# For example, to load a list of objects under a key 'items', you might use jq_schema=".items[]"
# To load a specific field 'answer', you might use jq_schema=".answer"
loader = JSONLoader(
    file_path=file_path,
    jq_schema='.', # This loads the entire JSON object
    text_content=False) # Set to True if the content you want to load is directly under the jq_schema path and is text

docs = loader.load()

"""####Process CSV Data"""

loader = CSVLoader(file_path='cleaned_googleplaystore.csv')
docs = loader.load_and_split()
##line docs = loader.load_and_split() reads your CSV file and creates a list called docs, where each element in the list represents a row from your CSV file, formatted as a document object that can be used in subsequent steps for tasks like creating embeddings and building a vector store.

"""####Add the splitted csv data to the vector store"""

vector_store.add_documents(documents=docs)

"""####Create teh Retrieval Chain"""

from langchain_core.prompts import ChatPromptTemplate
from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain

retriever = vector_store.as_retriever()

# Set up system prompt
system_prompt = (
    """
    You are a helpful chatbot.
    """
    "{context}"
    ###update the system prompt on however you like it to work - either for query insights or querying dataset
)

prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    ("human", "{input}"),

])

# Create the question-answer chain
question_answer_chain = create_stuff_documents_chain(llm, prompt)
rag_chain = create_retrieval_chain(retriever, question_answer_chain)

"""#### Chatbot Interface"""

while True:
    user_input = input("You: ")
    if user_input.lower() == 'quit':
        break
    response = rag_chain.invoke({"input": user_input})
    print(f"Bot: {response['answer']}")