# -*- coding: utf-8 -*-
"""insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-eY9TPv9NcEl7ESuAV2m4ILuOeeil4Lf

####Package Installation
"""

!pip install faiss-cpu langchain langchain-community langchain-google-genai pandas

"""####Imports"""

from langchain_community.document_loaders.csv_loader import CSVLoader
from pathlib import Path
from langchain.chat_models import init_chat_model
from langchain_google_genai import GoogleGenerativeAIEmbeddings
import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"]=userdata.get('GOOGLE_API_KEY')

llm = init_chat_model("gemini-2.5-flash", model_provider="google_genai")

"""####load the dataset"""

import pandas as pd

df = pd.read_csv('cleaned_googleplaystore.csv')

"""####Initiate the Vector Store"""

pip install -qU langchain-huggingface

import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
index = faiss.IndexFlatL2(len(embeddings.embed_query(" ")))
vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={}
)

"""####Process CSV Data"""

loader = CSVLoader(file_path='cleaned_googleplaystore.csv')
docs = loader.load_and_split()
##line docs = loader.load_and_split() reads your CSV file and creates a list called docs, where each element in the list represents a row from your CSV file, formatted as a document object that can be used in subsequent steps for tasks like creating embeddings and building a vector store.

"""####Add the splitted csv data to the vector store"""

vector_store.add_documents(documents=docs)

"""####Create teh Retrieval Chain"""

from langchain_core.prompts import ChatPromptTemplate
from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain

retriever = vector_store.as_retriever()

# Set up system prompt
system_prompt = (
    """
    You are an expert Applied AI Engineer specializing in app marketing and strategy.
Your task is to analyze app store data and provide actionable insights and recommendations.
Focus on identifying trends, popular categories, monetization strategies, user engagement factors, and potential market opportunities based on the provided data.
Provide clear, concise, and data-driven insights.
    """
    "{context}"
)

prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    ("human", "{input}"),

])

# Create the question-answer chain
question_answer_chain = create_stuff_documents_chain(llm, prompt)
rag_chain = create_retrieval_chain(retriever, question_answer_chain)

"""####Query the RAG bot with a question based on the CSV data"""

answer= rag_chain.invoke({"input": "Give insights on the dataset"})
answer['answer']

"""#### Save the response to a JSON file for insights"""

import json

response_data = {
    "input": answer['input'],
    "context": [doc.page_content for doc in answer['context']], # Extracting content from Document objects
    "answer": answer['answer']
}

with open('app_insights.json', 'w') as f:
    json.dump(response_data, f, indent=4)

print("Response saved to app_insights.json")

answer= rag_chain.invoke({"input": "Give me some app recommendations "})
answer['answer']

import json

response_data = {
    "input": answer['input'],
    "context": [doc.page_content for doc in answer['context']], # Extracting content from Document objects
    "answer": answer['answer']
}

with open('recommendations.json', 'w') as f:
    json.dump(response_data, f, indent=4)

print("Response saved to recommendations.json")